table Country_Metadata
	lineageTag: a3e5d712-4c91-4e89-8d14-3a5f78b9c1d2

	column Country_Code
		dataType: string
		lineageTag: b1c2d3e4-5f6a-7b8c-9d0e-1f2a3b4c5d6e
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	column Country_Name
		dataType: string
		lineageTag: c2d3e4f5-6a7b-8c9d-0e1f-2a3b4c5d6e7f
		summarizeBy: none
		sourceColumn: Country_Name

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: d3e4f5a6-7b8c-9d0e-1f2a-3b4c5d6e7f8a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Income Group'
		dataType: string
		lineageTag: e4f5a6b7-8c9d-0e1f-2a3b-4c5d6e7f8a9b
		summarizeBy: none
		sourceColumn: Income_Group

		annotation SummarizationSetBy = Automatic

	column GDP_Per_Capita
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f5a6b7c8-9d0e-1f2a-3b4c-5d6e7f8a9b0c
		summarizeBy: sum
		sourceColumn: GDP_Per_Capita

		annotation SummarizationSetBy = Automatic

	column Students_Assessed
		dataType: int64
		formatString: #,0
		lineageTag: a6b7c8d9-0e1f-2a3b-4c5d-6e7f8a9b0c1d
		summarizeBy: sum
		sourceColumn: Students_Assessed

		annotation SummarizationSetBy = Automatic

	partition Country_Metadata = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("c:\Users\Damon\Documents\School\PowerBI\Research with AI\datasets\Country_Metadata.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country_Code", type text}, {"Country_Name", type text}, {"Region", type text}, {"Income_Group", type text}, {"GDP_Per_Capita", type number}, {"Students_Assessed", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

