table 'OECD PISA data'
	lineageTag: 3458e765-e14e-4901-ac03-181e53e0a299

	column index
		dataType: int64
		formatString: 0
		lineageTag: 93b86444-a586-4989-9c65-a6d7424f50e1
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	column LOCATION
		dataType: string
		lineageTag: 51404cdb-7a36-407f-9a24-60b75e2e6acc
		summarizeBy: none
		sourceColumn: LOCATION

		annotation SummarizationSetBy = Automatic

	column INDICATOR
		dataType: string
		lineageTag: 79899f62-747c-4934-ac27-5497c9ea1388
		summarizeBy: none
		sourceColumn: INDICATOR

		annotation SummarizationSetBy = Automatic

	column SUBJECT
		dataType: string
		lineageTag: 65ca3b94-de71-43ae-8cdf-39f3491598e6
		summarizeBy: none
		sourceColumn: SUBJECT

		annotation SummarizationSetBy = Automatic

	column TIME
		dataType: int64
		formatString: 0
		lineageTag: 959e6cf4-6fb6-4dc1-aa81-9a4c8c46c0c4
		summarizeBy: sum
		sourceColumn: TIME

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: d4721643-ae1c-458f-a40e-76733e0ec883
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Country Name' =
			COALESCE(
			    LOOKUPVALUE(Country_Metadata[Country_Name], Country_Metadata[Country_Code], 'OECD PISA data'[LOCATION]),
			    LOOKUPVALUE(refined_dataset[Country], refined_dataset[Country_Code], 'OECD PISA data'[LOCATION]),
			    'OECD PISA data'[LOCATION]
			)
		lineageTag: f6e9162f-812d-4a8f-91c5-f7ed8b740a0c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Pisa_Sub =
			SWITCH(
			    TRUE(),
			    'OECD PISA data'[INDICATOR] = "PISAREAD", "Reading",
			    'OECD PISA data'[INDICATOR] = "PISAMATH", "Mathematics",
			    'OECD PISA data'[INDICATOR] = "PISASCIENCE", "Science"
			)
		lineageTag: b1266ce9-6b3c-4b35-ab48-8752021161dc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Bin' = ROUNDDOWN('OECD PISA data'[Value] / 20, 0) * 20
		formatString: 0
		lineageTag: c2d3e4f5-a6b7-8c9d-0e1f-2a3b4c5d6e7f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country / Economy' = 'OECD PISA data'[Country Name]
		lineageTag: a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'PISA Subject' = 'OECD PISA data'[Pisa_Sub]
		lineageTag: b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Assessment Year' = 'OECD PISA data'[TIME]
		formatString: 0
		lineageTag: c3d4e5f6-a7b8-9c0d-1e2f-3a4b5c6d7e8f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'OECD PISA data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\powerbi-student-performance-PISA\datasets\OECD PISA data.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"LOCATION", type text}, {"INDICATOR", type text}, {"SUBJECT", type text}, {"TIME", Int64.Type}, {"Value", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([SUBJECT] = "TOT")),
				    #"Uppercased Text" = Table.TransformColumns(#"Filtered Rows",{{"LOCATION", Text.Upper, type text}})
				in
				    #"Uppercased Text"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

